# Form implementation generated from reading ui file 'finalresep.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ResepMasakanApp(object):
    def setupUi(self, ResepMasakanApp):
        ResepMasakanApp.setObjectName("ResepMasakanApp")
        ResepMasakanApp.resize(500, 680)
        self.verticalLayout = QtWidgets.QVBoxLayout(ResepMasakanApp)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelKategori = QtWidgets.QLabel(parent=ResepMasakanApp)
        self.labelKategori.setObjectName("labelKategori")
        self.verticalLayout.addWidget(self.labelKategori)
        self.kategori_filter = QtWidgets.QComboBox(parent=ResepMasakanApp)
        self.kategori_filter.setObjectName("kategori_filter")
        self.verticalLayout.addWidget(self.kategori_filter)
        self.labelCari = QtWidgets.QLabel(parent=ResepMasakanApp)
        self.labelCari.setObjectName("labelCari")
        self.verticalLayout.addWidget(self.labelCari)
        self.input_cari = QtWidgets.QLineEdit(parent=ResepMasakanApp)
        self.input_cari.setObjectName("input_cari")
        self.verticalLayout.addWidget(self.input_cari)
        self.list_resep = QtWidgets.QListWidget(parent=ResepMasakanApp)
        self.list_resep.setObjectName("list_resep")
        self.verticalLayout.addWidget(self.list_resep)
        self.labelDetail = QtWidgets.QLabel(parent=ResepMasakanApp)
        self.labelDetail.setObjectName("labelDetail")
        self.verticalLayout.addWidget(self.labelDetail)
        self.detail_resep = QtWidgets.QTextEdit(parent=ResepMasakanApp)
        self.detail_resep.setReadOnly(True)
        self.detail_resep.setObjectName("detail_resep")
        self.verticalLayout.addWidget(self.detail_resep)
        self.btn_tambah = QtWidgets.QPushButton(parent=ResepMasakanApp)
        self.btn_tambah.setObjectName("btn_tambah")
        self.verticalLayout.addWidget(self.btn_tambah)

        self.retranslateUi(ResepMasakanApp)
        QtCore.QMetaObject.connectSlotsByName(ResepMasakanApp)

    def retranslateUi(self, ResepMasakanApp):
        _translate = QtCore.QCoreApplication.translate
        ResepMasakanApp.setWindowTitle(_translate("ResepMasakanApp", "📖 Resep Masakan - ResepKu"))
        self.labelKategori.setText(_translate("ResepMasakanApp", "📚 Pilih Kategori"))
        self.labelCari.setText(_translate("ResepMasakanApp", "🔎 Cari Resep"))
        self.input_cari.setPlaceholderText(_translate("ResepMasakanApp", "Cari resep..."))
        self.labelDetail.setText(_translate("ResepMasakanApp", "📋 Detail Resep"))
        self.btn_tambah.setText(_translate("ResepMasakanApp", "➕ Tambah Resep"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ResepMasakanApp = QtWidgets.QWidget()
    ui = Ui_ResepMasakanApp()
    ui.setupUi(ResepMasakanApp)
    ResepMasakanApp.show()
    sys.exit(app.exec())
